{
 "title": "go gc heap bytes total",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "go gc heap frees bytes total",
   "type": "gauge",
   "description": "total number of bytes freed from the heap by the go garbage collector over the lifetime of the go process.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_gc_heap_frees_bytes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go gc duration seconds count",
   "type": "gauge",
   "description": "total number of completed garbage collection cycles in a go application.\n",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_gc_duration_seconds_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go gc duration by label",
   "type": "gauge",
   "description": "show gc duration per label",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go gc heap allocs objects total",
   "type": "gauge",
   "description": "total number of heap memory objects allocated by the go runtime since the application started.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_gc_heap_allocs_objects_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go gc gomemlimit bytes",
   "type": "barchart",
   "description": "the memory limit in bytes set for the go grabage collector.once the threshold reached gc is triggered to control memory usage.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 4 },
   "targets": [
    { "expr": "go_gc_gomemlimit_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "up",
   "type": "barchart",
   "description": "the up mertic shows whether a target monitored by prometheus is reachable 1 or not 0.",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 4 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "prometheus http request duration seconds sum",
   "type": "bargauge",
   "description": "this counter tracks the total cumulative duration in seconds spent by prometheus while handling http request.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_http_request_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus engine query duration seconds",
   "type": "piechart",
   "description": "this metric tracks the duration it takes for prometheus to execute queries.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process cpu seconds total",
   "type": "stat",
   "description": "this counter shows the total cumulative cpu time consumed by the process since it started.it includes both user and system time.",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "prometheus engine query samples total",
   "type": "histogram",
   "description": "this metric counts the total number of samples data points evaluated by the prometheus query engine since the server started.it reflects query wokload and complexity.",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "prometheus_engine_query_samples_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go sched pauses total gc seconds bucket",
   "type": "histogram",
   "description": "this metric shows how long goroutines were paused due to garbage collection,grouped into duration buckets.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "go_sched_pauses_total_gc_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus http requests total",
   "type": "histogram",
   "description": "this counter tracks the total number of http requests received by the prometheus server.",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 16 },
   "targets": [
    { "expr": "prometheus_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } }
 ]
}